In [8]:
%matplotlib inline

import numpy as np
import tensorflow as tf

D = 3;
D_Z = int(D*(D+1)/2);
_x = np.arange(D_Z);
x = tf.placeholder(tf.float32, shape=(None,));
feed_dict = {x:_x};
y = tf.contrib.distributions.fill_triangular(x);
z = tf.contrib.distributions.matrix_diag_transform(y, tf.exp);

sess = tf.Session();
_y, _z = sess.run([y,z], feed_dict);

print('y');
print(_y);

print('z');
print(_z);

y
[[3. 0. 0.]
 [5. 4. 0.]
 [2. 1. 0.]]
z
[[20.085537  0.        0.      ]
 [ 5.       54.59815   0.      ]
 [ 2.        1.        1.      ]]


In [11]:
x = tf.placeholder(tf.float32, shape=(3,4,5));
y = tf.placeholder(tf.float32, shape=(1,1,5));
z = tf.pow(x,y);

_x = 2*np.ones((3,4,5));
_y = np.expand_dims(np.expand_dims(np.arange(5), 0), 0);
print(_y.shape);
feed_dict = {x:_x, y:_y};
_z = sess.run(z, feed_dict);
print('z', _z.shape);
print(_z)

(1, 1, 5)
z (3, 4, 5)
[[[ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]]

 [[ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]]

 [[ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]
  [ 1.  2.  4.  8. 16.]]]


In [ ]:
from scipy.stats import invwishart

D = 2;
Psi = np.eye()