In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

def drawPoissonRates(D):
    return np.random.uniform(0.001, 10, (D,));

def drawPoissonCounts(z, N):
    D = z.shape[0];
    x = np.zeros((D,N));
    for i in range(D):
        x[i,:] = np.random.poisson(z[i], (N,));
    return x;

z = drawPoissonRates(5);
print(z);
x = drawPoissonCounts(z, 10);
print(x)

[7.10617911 4.50576329 9.92194085 4.48326078 5.44257797]
[[ 7.  9.  7.  7.  5.  7. 10.  4.  9.  8.]
 [ 5.  5.  5.  3.  5.  3.  5.  6.  3.  3.]
 [ 8.  9.  7.  7. 11. 14. 10.  7.  9. 10.]
 [ 6.  5.  3.  5.  3.  4.  5.  4.  3.  3.]
 [ 8.  1.  3.  3.  4.  4.  5.  7.  2.  3.]]
